src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Surname = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column]
    private ?int $Age = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSurname(): ?string
    {
        return $this->Surname;
    }

    public function setSurname(string $Surname): self
    {
        $this->Surname = $Surname;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }
}

src/Controller/UserAdminController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/user')]
class UserAdminController extends AbstractController
{
    #[Route('/', name: 'app_user_admin_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user_admin/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_user_admin_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user_admin/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}', name: 'app_user_admin_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_admin_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user_admin/index.html.twig
{% extends 'admin/base.html.twig' %}
{% block body %}
    <h1 class="my-3 mx-auto text-center">Utilisateurs</h1>
    <table class="table container bg-white shadow-sm">
        <thead>
        <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Roles</th>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Numero</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.numero }}</td>
                <td>
                    <a href="{{ path('app_user_admin_show', {'id': user.id}) }}" class="btn btn-primary w-100">Afficher</a>
                    <form method="post" action="{{ path('app_user_admin_delete', {'id': user.id}) }}"
                          onsubmit="return confirm('Are you sure you want to delete this item?');"
                          class="">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
                        <button class="btn btn-danger  w-100 mt-3">Supprimer</button>
                    </form>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/user_admin/show.html.twig
{% extends 'admin/base.html.twig' %}
{% block body %}
    <div class="container mt-5">
        <h1>Utilisateur</h1>
        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Numero</th>
                <td>{{ user.numero }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ user.photo }}</td>
            </tr>
            </tbody>
        </table>

        <div class="row">
            <a href="{{ path('app_user_admin_index') }}" class="col-md-2 btn btn-primary">
            <i class="fa fa-backward"></i>
                &nbsp&nbsp&nbspRevenir a la liste
            </a>
            <form method="post" action="{{ path('app_user_admin_delete', {'id': user.id}) }}"
                  onsubmit="return confirm('Are you sure you want to delete this item?');"
                  class="col-md-3">
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
                <button class="btn btn-danger">Supprimer</button>
            </form>
        </div>
    </div>
{% endblock %}